title: "M. Abbas | Tech & Engineering"
description: "Personal portfolio and blog of M. Abbas, Computer Engineering Student at UET"
baseurl: "" # leave empty for root
url: "http://localhost:4000"
theme: minima
markdown: kramdown
permalink: /:title/
